services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      HTTP_ADDR: ":8080"
      OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
      OTEL_SERVICE_NAME: "o11y-starter"
    depends_on:
      otel-collector:
        condition: service_started
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - ./otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "13133:13133"
