{{- if eq .Values.secret.type "native" -}}
{{- if .Values.secret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "o11y-starter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "o11y-starter.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- else }}
  {{- fail "secret.type is \"native\" but secret.data is empty — add at least one key/value pair or set secret.type to \"none\"" }}
{{- end }}
{{- end }}
